import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import nodemailer from "nodemailer";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();

app.use(cors());
app.use(express.json());

// =========================
// GEMINI
// =========================

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});
console.log("Gemini API key loaded:", !!process.env.GEMINI_API_KEY);
// =========================
// TEST SERVER
// =========================

app.get("/", (req, res) => {
  res.send("AURA AI server is running 💗");
});

// =========================
// AURA CHAT
// =========================

app.post("/chat", async (req, res) => {
  try {
    const messages = req.body.messages || [];

    const conversation = messages
      .map((message) => {
        const speaker =
          message.sender === "user" ? "User" : "AURA";

        return `${speaker}: ${message.text}`;
      })
      .join("\n");

    const prompt = `
You are AURA, a warm and supportive female superhero who helps girls and women understand their bodies, periods, emotions, wellbeing and everyday concerns.

PERSONALITY:
- Warm and calm
- Friendly and natural
- Never judgmental
- Empowering
- Speak like a caring older sister
- Use simple language
- Occasionally use tasteful emojis
- Keep responses reasonably short

SAFETY:
- You are not a doctor.
- Do not diagnose medical conditions.
- Do not give dangerous medical instructions.
- For serious or emergency symptoms, encourage the visitor to contact a qualified healthcare professional or emergency service.
- For children, keep explanations age-appropriate and educational.
- Never shame the visitor.

CONVERSATION:

${conversation}

Respond naturally to the visitor's latest message.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
    });

    res.json({
      reply: response.text,
    });

  } catch (error) {
    console.error("Gemini error:", error);

    res.status(500).json({
      reply:
        "I'm having a little trouble connecting right now. Please try again in a moment. 💗",
    });
  }
});

// =========================
// EMAIL
// =========================

const transporter = nodemailer.createTransport({
  service: "gmail",

  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },

  tls: {
    rejectUnauthorized: false,
  },
});

// =========================
// SUBMIT REQUEST
// =========================

app.post("/submit-request", async (req, res) => {
  try {
    const {
      concern,
      name,
      age,
      email,
      location,
    } = req.body;

    if (!concern || !name || !age || !email || !location) {
      return res.status(400).json({
        error: "Please provide all required information.",
      });
    }

    const submittedAt = new Date().toLocaleString("en-IN", {
      dateStyle: "full",
      timeStyle: "short",
    });

    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: process.env.EMAIL_USER,

      subject: "🦸 Someone Needs Your Help!",

      html: `
        <div style="
          font-family: Arial, sans-serif;
          max-width: 600px;
          margin: auto;
          padding: 25px;
          background: #fff5fa;
          border-radius: 15px;
        ">

          <h2 style="color: #d85b91;">
            🦸 Someone Needs Your Help!
          </h2>

          <p>
            Someone has requested AURA's help through the website.
          </p>

          <hr>

          <h3 style="color: #d85b91;">
            Visitor Details
          </h3>

          <p>
            <strong>Name:</strong> ${name}
          </p>

          <p>
            <strong>Age:</strong> ${age}
          </p>

          <p>
            <strong>Location:</strong> ${location}
          </p>

          <p>
            <strong>Email:</strong> ${email}
          </p>

          <h3 style="color: #d85b91;">
            Grievance / Request
          </h3>

          <div style="
            background: white;
            padding: 15px;
            border-radius: 10px;
          ">
            ${concern}
          </div>

          <h3 style="color: #d85b91;">
            Submission Details
          </h3>

          <p>
            <strong>Date & Time:</strong> ${submittedAt}
          </p>

          <hr>

          <p style="color: #777; font-size: 13px;">
            This email was automatically generated by the AURA website.
          </p>

        </div>
      `,
    });

    console.log("Email sent successfully 💗");

    res.json({
      success: true,
      message: "Request submitted successfully.",
    });

  } catch (error) {
    console.error("Email error:", error);

    res.status(500).json({
      error: "Failed to send email.",
    });
  }
});

// =========================
// START SERVER
// =========================

const PORT = process.env.PORT || 3001;

app.listen(PORT, () => {
  console.log("");
  console.log("====================================");
  console.log("💗 AURA AI SERVER IS RUNNING");
  console.log(`🌐 Server running on port ${PORT}`);
  console.log("====================================");
  console.log("DO NOT CLOSE THIS TERMINAL.");
});
